name: ExtUtils::AutoInstall
version: 0.53
abstract: Automatic install of dependencies via CPAN
author: Autrijus Tang (autrijus@autrius.org)
distribution_type: module
requires:
  Cwd: 0
  Carp: 0
  ExtUtils::Manifest: 0
  ExtUtils::MakeMaker: 0
private:
  directory:
    - inc
generated_by: Module::Install version 0.23
